### ISSUE TITLE
possible fullscreen tool issue

### ISSUE THREAD

**Issue by jsoldenwagner** [nationalparkservice/projects#1]
![full screen issue](https://cloud.githubusercontent.com/assets/14880872/11882703/e6f89c4e-a4c2-11e5-93b5-ac44f1904c43.jpg)

Nate,

Tried using the fullscreen tool on my boss's computer and received the above message about iFrames.  Has only happened once so I'm not sure it's really a concern, but I thought it made sense to let you know about it.

Regards,

Jim

**Comment by nateirwin** [comment]
Hi Jim,

You're seeing this message because maps embedded in iframes cannot access resources on the parent page. Because of this, the fullscreen and hash controls will only work if a map is embedded in a web pages served on an .nps.gov address.
