### ISSUE TITLE
other minor zoom control issues

### ISSUE THREAD

**Issue by jsoldenwagner** [nationalparkservice/projects#2]
You might also be interested in this:

![screen shot 2015-12-18 at 3 07 22 pm](https://cloud.githubusercontent.com/assets/14880872/11909314/f120665c-a599-11e5-96f0-3655ddb744a2.png)

This happens somewhat often, where the map loads and the controls are active but one or more of them do not have symbols indicating their function.  Not sure if this is just my map, all npmaps, or some Yosemite internet issue.  Again, just letting you know.  Also, is this the appropriate way to communicate these sorts of things, or should I just email you or the npmap team?

**Comment by nateirwin** [comment]
What version of the library are you loading? This looks like a content delivery network issue.

About reporting these issues: They're great, but ideally you would report them in the NPMap.js issue tracker: https://github.com/nationalparkservice/npmap.js/issues.

**Comment by jsoldenwagner** [comment]
s.src = 'http://www.nps.gov/lib/npmap.js/3.0.2/npmap-bootstrap.min.js';

looks like 3.0.2

Should I change this on github?

J.

**Comment by nateirwin** [comment]
Yeah, you're seeing a CDN issue. I'm working with Web Services to hopefully get it resolved.

In the meantime, you may want to update to 3.0.8 (just change 3.0.2 to 3.0.8), as it's the latest version. I'm going to close this issue for now.

**Comment by nateirwin** [comment]
This is actually resolved now. Took us awhile to track it down, but it ended up being a configuration issue on one of the eight content delivery servers.
